### Working with the Multiple Linear Regression

In [35]:
import numpy as np 
import pandas as pd


In [36]:
data ={
    'size':[1000,1100,1200,1300,1400],
    'Bedroom':[1,2,3,4,5],
    'Age':[21,22,23,24,25],
    'price':[100000,110000,120000,130000,140000]
}

In [37]:
df = pd.DataFrame(data)

X = df[['size','Bedroom','Age']]
y = df['price']

In [38]:
X.insert(0,'Intercept',1)
X = np.array(X)
y = np.array(y).reshape(-1,1)


In [39]:
X

array([[   1, 1000,    1,   21],
       [   1, 1100,    2,   22],
       [   1, 1200,    3,   23],
       [   1, 1300,    4,   24],
       [   1, 1400,    5,   25]])

In [40]:
y

array([[100000],
       [110000],
       [120000],
       [130000],
       [140000]])

In [41]:
beta = np.linalg.pinv(X.T @ X) @ X.T @ y

In [42]:
beta

array([[-9.85026612e-03],
       [ 9.99802010e+01],
       [ 1.08845440e+00],
       [ 8.91449082e-01]])

In [45]:
new = np.array([1,1400,5,25])
y_pred = new @ beta
y_pred     # Getting predicted output same as actual output

array([140000.])