### Implementing Multiple Linear Regression Using Gradient Descent

### In this MLR we solve The bias abd weights differnrtly(theta0 and Theta1,2,3,..  has differnt Formula )

In [159]:
import numpy as np

# Sample data (replace with your actual data)
# X should be a 2D array where each row is a sample and each column is a feature
# y should be a 1D array of target values
X = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])
y = np.array([10, 20, 30, 40])



In [160]:
# Hyperparameters
learning_rate = 0.01
n_iterations = 2201



In [161]:
# Initialize parameters
n_samples, n_features = X.shape
weights = np.zeros(n_features)
bias = 0
print(n_samples)
print(n_features)
print(weights)
print(bias)

4
2
[0. 0.]
0


In [162]:
# Gradient descent
for iteration in range(n_iterations):
    # Calculate predictions
    y_predicted = np.dot(X, weights) + bias
    print(y_predicted)
    
    # Compute gradients
    dw = (1/n_samples) * np.dot(X.T, (y_predicted - y))
    db = (1/n_samples) * np.sum(y_predicted - y)
    
    # Update parameters
    weights -= learning_rate * dw
    bias -= learning_rate * db
    print(weights)
    print(bias)
    # Calculate and print cost every 100 iterations (optional)
    if iteration % 100 == 0:
        cost = (1/(2*n_samples)) * np.sum((y_predicted - y)**2)
        print(f"Iteration {iteration}, Cost: {cost:.4f}")



[0. 0. 0. 0.]
[0.75 0.75]
0.25
Iteration 0, Cost: 375.0000
[1.75 3.25 4.75 6.25]
[1.38125 1.38125]
0.45999999999999996
[ 3.2225  5.985   8.7475 11.51  ]
[1.9125625 1.9125625]
0.6363375
[ 4.4614625  8.2865875 12.1117125 15.9368375]
[2.35976969 2.35976969]
0.784346
[ 5.50388538 10.22342475 14.94296412 19.6625035 ]
[2.73619558 2.73619558]
0.908514055625
[ 6.38090522 11.85329639 17.32568756 22.79807873]
[3.0530534 3.0530534]
1.01261913585
[ 7.11872593 13.22483272 19.33093951 25.4370463 ]
[3.31977991 3.31977991]
1.099840274725094
[ 7.73940009 14.37895991 21.01851972 27.65807954]
[3.54431691 3.54431691]
1.17285287659621
[ 8.26148671 15.35012054 22.43875436 29.52738819]
[3.73334806 3.73334806]
1.2339085020992664
[ 8.70060461 16.16730072 23.63399684 31.10069295]
[3.89249813 3.89249813]
1.2849020143026848
[ 9.06989828 16.85489455 24.63989082 32.42488709]
[4.02650086 4.02650086]
1.3274280874280313
[ 9.38042982 17.43343154 25.48643327 33.539435  ]
[4.13934003 4.13934003]
1.3628287633497467
[ 9.64

In [163]:
# Print final parameters
print("\nFinal parameters:")
print("Weights:", weights)
print("Bias:", bias)

# Make predictions
X_test = np.array([[8, 8]])
predictions = np.dot(X_test, weights) + bias
print("\nPredictions for test data:")
print(predictions)


Final parameters:
Weights: [4.99169615 4.99169615]
Bias: 0.04929893010937962

Predictions for test data:
[79.91643736]
