### Simple Polynomial Regression Using Normal Equation (Analytical Method)


In [1]:
import numpy as np

In [2]:
X = np.array([1,2,3,4,5])
y = np.array([3,9,28,65,126])

#### Adding Polynomials

In [4]:
X_poly = np.vstack((np.ones(len(X)),X,X**2,X**3))

In [5]:
X_poly

array([[  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5.],
       [  1.,   4.,   9.,  16.,  25.],
       [  1.,   8.,  27.,  64., 125.]])

#### In the above formula the values will be added as Rows but we want it as Column so in below step. We Did Transpose(.T)

In [6]:
X_poly = X_poly.T

In [7]:
X_poly

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   4.,  16.,  64.],
       [  1.,   5.,  25., 125.]])

In [16]:
theta = np.linalg.inv(X_poly.T @ X_poly) @ X_poly.T @ y

In [17]:
theta

array([ 4.2       , -3.02380952,  0.89285714,  0.91666667])

#### Predicting New term

In [27]:
age = 4
y_pred = theta[0] + theta[1]*age + theta[2]*age**2 + theta[3]*age**3
print(f"Price when age is 4 : {y_pred:.2f}")

Price when age is 4 : 65.06
