### Multiple Polynomial Regression Using Normal Equation

In [144]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [145]:
x = np.array([[1,2],[2,1],[3,4]])

In [146]:
y = np.array([6,8,15]).reshape(-1,1)

In [147]:
poly = PolynomialFeatures(degree=2,include_bias=True)
x_poly = poly.fit_transform(x)
x_poly

array([[ 1.,  1.,  2.,  1.,  2.,  4.],
       [ 1.,  2.,  1.,  4.,  2.,  1.],
       [ 1.,  3.,  4.,  9., 12., 16.]])

In [148]:
theta = np.linalg.pinv(x_poly.T @ x_poly) @ x_poly.T @ y
theta = theta.flatten()            # amkes it as 1D

In [149]:
theta

array([ 1.36242138,  1.3577044 ,  1.52044025,  0.74371069, -0.29795597,
        0.02279874])

In [150]:
print("Theta values:", theta)

Theta values: [ 1.36242138  1.3577044   1.52044025  0.74371069 -0.29795597  0.02279874]


In [151]:
x_new = np.array([[1,2]])
x_new1 = poly.fit_transform(x_new)

In [152]:
x_new1

array([[1., 1., 2., 1., 2., 4.]])

In [153]:
y_pred = np.dot(x_new1,theta)

In [ ]:
y_pred   # Output is same as above input trained data so model is valid

array([6.])